# Generated by Django 5.2.2 on 2025-06-08 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registroacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
