# Generated by Django 5.1.6 on 2025-04-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplan',
            name='plan_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
