# Generated by Django 5.1.6 on 2025-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditplan_plan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='audit_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
