# Generated by Django 5.1.6 on 2025-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_checklist_audit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='process_type',
            field=models.CharField(default='Ciclo de vida', max_length=255),
        ),
    ]
