# Generated by Django 5.1.6 on 2025-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_checklist_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conformidades_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='fortalezas_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='no_conformidades_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='recomendaciones_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='resumen_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='report',
            name='riesgos_data',
            field=models.TextField(default='[]'),
        ),
    ]
