# Generated by Django 5.1.6 on 2025-04-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_report_conformidades_data_report_fortalezas_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='adecuacion_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='eficacia_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='report',
            name='pertinencia_data',
            field=models.TextField(default='[]'),
        ),
    ]
