# Generated by Django 5.2.4 on 2025-12-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_report_adecuacion_data_report_eficacia_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-id'], 'verbose_name': 'Lista de Verificación', 'verbose_name_plural': 'Listas de Verificación'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Reporte de Auditoría', 'verbose_name_plural': 'Reportes de Auditoría'},
        ),
        migrations.AddField(
            model_name='checklist',
            name='audit_plan',
            field=models.ForeignKey(blank=True, help_text='Plan de auditoría al que pertenece este checklist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='audit.auditplan'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='checklist',
            field=models.ManyToManyField(related_name='reports', to='audit.checklist'),
        ),
    ]
