# Generated by Django 5.1.6 on 2025-03-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_auditor_lider', models.BooleanField(default=False)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('lista_clausulas', models.TextField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.organizacion')),
                ('auditor_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('lista_clausulas', models.TextField()),
                ('dependencia', models.CharField(max_length=255)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.organizacion')),
                ('auditor_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('lista_clausulas', models.TextField()),
                ('lista_verificacion', models.ManyToManyField(to='AudiAppApp.listaverificacion')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.organizacion')),
                ('auditor_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudiAppApp.usuario')),
            ],
        ),
    ]
